jobs:
  - id: check-disk-space
    name: "System Health Check"
    steps:
      - "df -h"
      - "free -m"
      - "uptime"
  
  - id: system-status
    name: "check what is the system version"
    steps:
      - "lsb_release -a"
      - "uptime"